language: objective-c
osx_image: xcode9.1
script:
    - xcodebuild clean test -project BioSwift.xcodeproj -scheme BioSwift-Package -destination "platform=iOS Simulator,name=iPhone 7,OS=11.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
