language: objective-c
osx_image: xcode9.1
env:
  - TOOLCHAINS=swift
script:
  - swift package fetch
  - swift build
  - swift test
before_install:
  - curl -O https://swift.org/builds/swift-4.0-branch/xcode/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-10-08-a/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-10-08-a-osx.pkg
  - sudo installer -pkg swift-4.0-DEVELOPMENT-SNAPSHOT-2017-10-08-a-osx.pkg -target /